// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDFVPzibFS7ozNFJdiiM_1WYKy1JeqlZPU',
    appId: '1:573548903389:web:97cc0dba711790306f5434',
    messagingSenderId: '573548903389',
    projectId: 'dbquest-74b96',
    authDomain: 'dbquest-74b96.firebaseapp.com',
    storageBucket: 'dbquest-74b96.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCP3YZkaDQYiF3goF8frZykIYrhv1KWaZw',
    appId: '1:573548903389:android:7a8af20cf08a3b7e6f5434',
    messagingSenderId: '573548903389',
    projectId: 'dbquest-74b96',
    storageBucket: 'dbquest-74b96.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4Zu1hQZTSmpdNn96GOAiEKALjB5Z7KUA',
    appId: '1:573548903389:ios:c25a5e36263dba256f5434',
    messagingSenderId: '573548903389',
    projectId: 'dbquest-74b96',
    storageBucket: 'dbquest-74b96.firebasestorage.app',
    iosBundleId: 'com.example.dbapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4Zu1hQZTSmpdNn96GOAiEKALjB5Z7KUA',
    appId: '1:573548903389:ios:c25a5e36263dba256f5434',
    messagingSenderId: '573548903389',
    projectId: 'dbquest-74b96',
    storageBucket: 'dbquest-74b96.firebasestorage.app',
    iosBundleId: 'com.example.dbapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDFVPzibFS7ozNFJdiiM_1WYKy1JeqlZPU',
    appId: '1:573548903389:web:de3881c2b65d2dad6f5434',
    messagingSenderId: '573548903389',
    projectId: 'dbquest-74b96',
    authDomain: 'dbquest-74b96.firebaseapp.com',
    storageBucket: 'dbquest-74b96.firebasestorage.app',
  );
}
